"""novie-agent-sdk: A2A Agent Runtime SDK.

主路径 (A2A Runtime SDK)：
  Agent.from_manifest(".well-known/agent.json")
  agent.task(handler)
  agent.serve()
"""
from .agent_yaml import (
    AgentType,
    AgentYamlAdvanced,
    AgentYamlConfig,
    AgentYamlGovernance,
    AgentYamlIdentity,
    AgentYamlInputs,
    AgentYamlOutputs,
    AgentYamlRouting,
    AgentYamlRuntime,
    GovernanceRisk,
    GovernanceSideEffect,
    RuntimeDuration,
)
from .artifact_facade import (
    ArtifactAgentApp,
    ArtifactAgentContext,
    ArtifactResult,
    NeedsConfirmationResult,
    artifact_agent,
)
from .manifest_generator import generate_agent_manifest
from .manifest_validator import (
    ManifestValidationIssue,
    ManifestValidationResult,
    Severity,
    validate_agent_yaml,
    validate_agent_yaml_and_manifest,
    validate_generated_manifest,
)
from .call_scope import extract_call_scope
from .project_brief import extract_project_brief, render_brief_for_prompt
from .observability import (
    AgentObservability,
    LangfuseObservabilitySink,
    NoOpObservabilitySink,
    NovieLangChainCallbackHandler,
    UsageReport,
)
from .testing import (
    assert_http_json_agent_card,
    assert_http_json_healthcheck,
    assert_http_json_invoke_contract,
    assert_http_json_invoke_idempotency_replay,
    assert_http_json_stream_contract,
    assert_http_json_stream_idempotency_replay,
    assert_http_json_tasks_idempotency_replay,
)

# A2A runtime SDK — always available (FastAPI required only for .serve())
from .runtime import (
    Agent,
    InMemoryTaskStore,
    InvokeContext,
    RegistrationClient,
    RequestHeaders,
    SqliteOneShotInvocationStore,
    SqliteTaskStore,
    StreamContext,
    TaskStore,
    TaskContext,
    TaskRecord,
)
from .platform_callback import (
    PlatformCallbackClient,
    build_platform_callback_headers,
    sign_platform_callback_headers,
)
from .conformance import (
    CompatibilityMatrix,
    ConformanceProbe,
    ConformanceReport,
    MANIFEST_SCHEMA_VERSION,
    PLATFORM_PROTOCOL_VERSION,
    RestartHook,
    SDK_VERSION,
    SUPPORTED_AGENT_KINDS,
    SUPPORTED_PROTOCOL_MODES,
    current_compatibility,
    run_conformance,
    verify_compatibility,
)
from .platform_namespace import (
    CapabilityCallDiagnostics,
    CheckpointsNamespace,
    DegradationKind,
    KnowledgeNamespace,
    PlatformNamespace,
    PlatformNamespaceProtocol,
    build_platform_namespace,
    classify_envelope_error,
)
from .provider_authoring import (
    FileProviderRegistryWriter,
    ProviderFolderOutcome,
    ProviderIssueSeverity,
    ProviderRegistrationCategory,
    ProviderRegistrationOutcome,
    ProviderRegistryWriter,
    ProviderValidationIssue,
    ProviderValidationResult,
    load_provider_folder,
    register_provider_folder,
)
from .provider_conformance import (
    ProviderConformanceProbe,
    ProviderConformanceReport,
    ProviderRuntimeConformanceConfig,
    run_provider_conformance,
)
from .openapi_provider import (
    GeneratorError,
    OperationSemantics,
    SemanticsHints,
    UnmappedOperationDescriptor,
    UnmappedOperationsError,
    UnsupportedOpenAPIError,
    bootstrap_semantics_from_openapi,
    generate_capabilities,
    generate_provider_files,
    load_semantics,
    operation_ids,
)
from .worker_facade import (
    HumanWaitRequest,
    WorkerAgentApp,
    WorkerFailure,
    WorkerResult,
    WorkerTaskContext,
    worker_agent,
)

__all__ = [
    # agent.yaml authoring schema (EXPERT_AGENT_SDK W1)
    "AgentType",
    "AgentYamlAdvanced",
    "AgentYamlConfig",
    "AgentYamlGovernance",
    "AgentYamlIdentity",
    "AgentYamlInputs",
    "AgentYamlOutputs",
    "AgentYamlRouting",
    "AgentYamlRuntime",
    "GovernanceRisk",
    "GovernanceSideEffect",
    "RuntimeDuration",
    "generate_agent_manifest",
    # artifact_agent SDK facade (EXPERT_AGENT_SDK W3)
    "ArtifactAgentApp",
    "ArtifactAgentContext",
    "ArtifactResult",
    "NeedsConfirmationResult",
    "artifact_agent",
    "ManifestValidationIssue",
    "ManifestValidationResult",
    "Severity",
    "validate_agent_yaml",
    "validate_agent_yaml_and_manifest",
    "validate_generated_manifest",
    # A2A runtime SDK (primary path)
    "Agent",
    "InMemoryTaskStore",
    "InvokeContext",
    "RegistrationClient",
    "RequestHeaders",
    "SqliteOneShotInvocationStore",
    "SqliteTaskStore",
    "StreamContext",
    "TaskStore",
    "TaskContext",
    "TaskRecord",
    "PlatformCallbackClient",
    # Platform callback namespace (EXPERT_AGENT_SDK W4)
    "CapabilityCallDiagnostics",
    "CheckpointsNamespace",
    "DegradationKind",
    "KnowledgeNamespace",
    "PlatformNamespace",
    "PlatformNamespaceProtocol",
    "build_platform_namespace",
    "classify_envelope_error",
    # Conformance + compatibility matrix (EXPERT_AGENT_SDK W8)
    "CompatibilityMatrix",
    "ConformanceProbe",
    "ConformanceReport",
    "MANIFEST_SCHEMA_VERSION",
    "PLATFORM_PROTOCOL_VERSION",
    "RestartHook",
    "SDK_VERSION",
    "SUPPORTED_AGENT_KINDS",
    "SUPPORTED_PROTOCOL_MODES",
    "current_compatibility",
    "run_conformance",
    "verify_compatibility",
    # worker_agent SDK facade (EXPERT_AGENT_SDK W5)
    "HumanWaitRequest",
    "WorkerAgentApp",
    "WorkerFailure",
    "WorkerResult",
    "WorkerTaskContext",
    "worker_agent",
    "AgentObservability",
    "LangfuseObservabilitySink",
    "NoOpObservabilitySink",
    "NovieLangChainCallbackHandler",
    "UsageReport",
    "build_platform_callback_headers",
    "extract_call_scope",
    "extract_project_brief",
    "load_provider_folder",
    "ProviderConformanceProbe",
    "ProviderConformanceReport",
    "ProviderRuntimeConformanceConfig",
    "register_provider_folder",
    "run_provider_conformance",
    # OpenAPI provider auto-generation (OPENAPI_PROVIDER_AUTOGEN W1)
    "GeneratorError",
    "OperationSemantics",
    "SemanticsHints",
    "UnmappedOperationDescriptor",
    "UnmappedOperationsError",
    "UnsupportedOpenAPIError",
    "bootstrap_semantics_from_openapi",
    "generate_capabilities",
    "generate_provider_files",
    "load_semantics",
    "operation_ids",
    "render_brief_for_prompt",
    "sign_platform_callback_headers",
    "assert_http_json_agent_card",
    "assert_http_json_healthcheck",
    "assert_http_json_invoke_contract",
    "assert_http_json_invoke_idempotency_replay",
    "assert_http_json_stream_contract",
    "assert_http_json_stream_idempotency_replay",
    "assert_http_json_tasks_idempotency_replay",
    "FileProviderRegistryWriter",
    "ProviderFolderOutcome",
    "ProviderIssueSeverity",
    "ProviderRegistrationCategory",
    "ProviderRegistrationOutcome",
    "ProviderRegistryWriter",
    "ProviderValidationIssue",
    "ProviderValidationResult",
]
